version: "3.7"
services:
  ttgen:
    container_name: ttgen
    environment: {}
    build:
      context: .
      dockerfile: Dockerfile
    image: ttgen:v1
    volumes:
      - venv:/application/venv
      - D:/Projects/tabletop_generator:/application/ttgen
      - C:/Users/kania/OneDrive/Documents/my games/Tabletop Simulator/Mods/Workshop/Testing:/application/output
    tty: true

volumes:
  venv:
